// Cart Constants
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
export const CART_ITEM_CLEAR = "CART_ITEM_CLEAR";
export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS";
export const SAVE_PAYMENT_METHOD = "SAVE_PAYMENT_METHOD";

// Order Constants
export const ORDER_REQ = "ORDER_REQ";
export const ORDER_RESET = "ORDER_RESET";
export const ORDER_FAIL = "ORDER_FAIL";
export const ORDER_SUCCESS = "ORDER_SUCCESS";

// Order Detail Constants
export const ORDER_DETAIL_REQ = "ORDER_DETAIL_REQ";
export const ORDER_DETAIL_REQ_FAIL = "ORDER_DETAIL_REQ_FAIL";
export const ORDER_DETAIL_REQ_SUCCESS = "ORDER_DETAIL_REQ_SUCCESS";

// Order Payment Constants
export const ORDER_PAYMENT_REQ = "ORDER_PAYMENT_REQ";
export const ORDER_PAYMENT_REQ_FAIL = "ORDER_PAYMENT_REQ_FAIL";
export const ORDER_PAYMENT_REQ_SUCCESS = "ORDER_PAYMENT_REQ_SUCCESS";

// Order List Constants
export const ORDER_LIST_REQ = "ORDER_LIST_REQ";
export const ORDER_LIST_REQ_FAIL = "ORDER_LIST_REQ_FAIL";
export const ORDER_LIST_REQ_SUCCESS = "ORDER_LIST_REQ_SUCCESS";
